# Generated by Django 5.0.6 on 2024-06-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('profile_desc', models.CharField(max_length=100)),
                ('profile_tags', models.CharField(max_length=100)),
            ],
        ),
    ]
